// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vixdang0x7d3/the-human-task-manager/internal/template"

func Signup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = template.Head().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <body><div class=\"flex items-center justify-center py-10\"><div class=\"card bg-base-200 w-120 shadow-xl\"><div class=\"card-body\" class=\"card-body items-center text-center\"><h2 class=\"card-title pb-4\">Sign up new account</h2><form hx-post=\"/v1/users\" hx-target=\"#card-body\"><div class=\"flex flex-col gap-2\"><label class=\"input input-bordered flex items-center gap-2\">Username: <input name=\"username\" id=\"username\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if true {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"text\" class=\"grow\" placeholder=\"taskman\"></label> <label class=\"input input-bordered flex items-center gap-2\">Email: <input name=\"email\" id=\"email\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if true {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"email\" class=\"grow\" placeholder=\"htm@site.com\"></label> <label class=\"input input-bordered flex items-center gap-2\">First Name: <input name=\"first_name\" id=\"first_name\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if true {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"text\" class=\"grow\" placeholder=\"Human\"></label> <label class=\"input input-bordered flex items-center gap-2\">Last Name: <input name=\"last_name\" id=\"last_name\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if true {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"text\" class=\"grow\" placeholder=\"Task Manager\"></label> <label class=\"input input-bordered flex items-center gap-2\">Password: <input name=\"password\" id=\"password\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if true {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" type=\"password\" class=\"grow\" placeholder=\"********\"></label></div><div class=\"card-actions justify-end pt-4\"><input type=\"submit\" value=\"Submit\" class=\"btn btn-primary\"> <a href=\"#!\" class=\"btn btn-secondary\">Cancel</a></div></form></div></div></div></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = template.Boilerplate().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
