// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects ("id", "user_id", "title")
VALUES ($1, $2, $3)
RETURNING id, user_id, title
`

type CreateProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Title  string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.UserID, arg.Title)
	var i Project
	err := row.Scan(&i.ID, &i.UserID, &i.Title)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects
WHERE id = $1
RETURNING id, user_id, title
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(&i.ID, &i.UserID, &i.Title)
	return i, err
}

const projectByID = `-- name: ProjectByID :one
SELECT id, user_id, title FROM projects
WHERE id = $1
`

func (q *Queries) ProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, projectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.UserID, &i.Title)
	return i, err
}
