// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: task_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const taskItemByID = `-- name: TaskItemByID :one
SELECT id, username, project_title, completed_by, description, priority, state, deadline, schedule, wait, "create", "end", tags, urgency FROM task_items
WHERE id=$1
`

func (q *Queries) TaskItemByID(ctx context.Context, id uuid.UUID) (TaskItem, error) {
	row := q.db.QueryRow(ctx, taskItemByID, id)
	var i TaskItem
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ProjectTitle,
		&i.CompletedBy,
		&i.Description,
		&i.Priority,
		&i.State,
		&i.Deadline,
		&i.Schedule,
		&i.Wait,
		&i.Create,
		&i.End,
		&i.Tags,
		&i.Urgency,
	)
	return i, err
}
